package com.gk.mybatis.generator.po;

import java.util.Date;

public class Acount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.id
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.name
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.balance
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.type
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.forwho
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String forwho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.money
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.remark
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.creator
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.createtime
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.modifier
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acount.modifytime
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.id
     *
     * @return the value of acount.id
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.id
     *
     * @param id the value for acount.id
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.name
     *
     * @return the value of acount.name
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.name
     *
     * @param name the value for acount.name
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.balance
     *
     * @return the value of acount.balance
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.balance
     *
     * @param balance the value for acount.balance
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.type
     *
     * @return the value of acount.type
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.type
     *
     * @param type the value for acount.type
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.forwho
     *
     * @return the value of acount.forwho
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getForwho() {
        return forwho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.forwho
     *
     * @param forwho the value for acount.forwho
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setForwho(String forwho) {
        this.forwho = forwho == null ? null : forwho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.money
     *
     * @return the value of acount.money
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.money
     *
     * @param money the value for acount.money
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.remark
     *
     * @return the value of acount.remark
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.remark
     *
     * @param remark the value for acount.remark
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.creator
     *
     * @return the value of acount.creator
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.creator
     *
     * @param creator the value for acount.creator
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.createtime
     *
     * @return the value of acount.createtime
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.createtime
     *
     * @param createtime the value for acount.createtime
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.modifier
     *
     * @return the value of acount.modifier
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.modifier
     *
     * @param modifier the value for acount.modifier
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acount.modifytime
     *
     * @return the value of acount.modifytime
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acount.modifytime
     *
     * @param modifytime the value for acount.modifytime
     *
     * @mbggenerated Sat Apr 02 17:10:24 CST 2016
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}